### ISSUE TITLE
Code doesn't work on iOS13.1.1, Xcode 11.1

### ISSUE THREAD

**Issue by phucnm** [egeniq/BetterSheet#2]
I just started writing some swiftUI code and ended up having the same issue on `sheet` as you. Code looks great but it doesn't seem to work on both simulators and my device. Prob Apple silently changed something?
I updated Xcode to 11.1 this morning and it seems to show modals multiple times normally (I'm pretty sure I could not in Xcode 11)

**Comment by petercv** [comment]
Thank you for reporting! Just tried with Xcode 11.1, but I haven't run into any issues yet. Can you describe what you exactly tried?

**Comment by petercv** [comment]
I looked into this, and the reason it doesn't work is because the example project doesn't initialise BetterSheet properly in the SceneDelegate. Unfortunately you can't just use UIHostingController, you need to call UIHostingController.withBetterSheetSupport(...). 

I also fixed some other issues in the example project in this pull request:
https://github.com/egeniq/BetterSheet/pull/3
